// ============================================================
// Doc Exporter - Generate documentation skeletons
// ============================================================
// Traverses the code graph to generate Markdown documentation
// with function signatures, parameter descriptions, and
// module dependency Mermaid diagrams.

import fs from 'fs';
import path from 'path';
import { SQLiteStore } from '../store/sqlite-store.js';
import type { Symbol, SymbolKind } from '../graph/types.js';

export interface DocExportOptions {
  /** Output directory */
  outputDir?: string;
  /** Include source code in docs */
  includeSource?: boolean;
  /** Include Mermaid dependency diagrams */
  includeDiagrams?: boolean;
  /** Generate per-file or per-module docs */
  granularity?: 'file' | 'module';
}

export interface DocExportResult {
  /** Number of files generated */
  filesGenerated: number;
  /** Output directory */
  outputDir: string;
  /** Summary text */
  summary: string;
}

/**
 * Generates documentation skeletons from the code graph.
 * Produces Markdown files with signatures, parameters, and
 * module dependency diagrams.
 */
export class DocExporter {
  private store: SQLiteStore;

  constructor(store: SQLiteStore) {
    this.store = store;
  }

  /**
   * Export documentation as Markdown files.
   */
  async export(projectPath: string, options?: DocExportOptions): Promise<DocExportResult> {
    const outputDir = options?.outputDir || path.join(projectPath, '.codeatlas', 'docs');
    const includeSource = options?.includeSource ?? false;
    const includeDiagrams = options?.includeDiagrams ?? true;
    const granularity = options?.granularity || 'file';

    // Ensure output directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    let filesGenerated = 0;

    // Get all symbols
    const allSymbols = this.store.searchSymbols('', { limit: 10000 });

    if (granularity === 'module') {
      filesGenerated = await this.generateModuleDocs(allSymbols, outputDir, includeSource, includeDiagrams);
    } else {
      filesGenerated = await this.generateFileDocs(allSymbols, outputDir, includeSource, includeDiagrams);
    }

    // Generate index
    this.generateIndex(allSymbols, outputDir, includeDiagrams);

    const summary = `📚 Documentation generated!\n- Files: ${filesGenerated + 1}\n- Output: ${outputDir}\n- Granularity: ${granularity}`;

    return { filesGenerated: filesGenerated + 1, outputDir, summary };
  }

  // ========================
  // File-level docs
  // ========================

  private async generateFileDocs(
    symbols: Symbol[],
    outputDir: string,
    includeSource: boolean,
    includeDiagrams: boolean,
  ): Promise<number> {
    // Group by file
    const byFile = new Map<string, Symbol[]>();
    for (const sym of symbols) {
      if (!byFile.has(sym.filePath)) byFile.set(sym.filePath, []);
      byFile.get(sym.filePath)!.push(sym);
    }

    let count = 0;
    for (const [filePath, fileSymbols] of byFile) {
      const content = this.renderFileDoc(filePath, fileSymbols, includeSource, includeDiagrams);
      const docPath = path.join(outputDir, this.sanitizeFilename(filePath) + '.md');
      const dir = path.dirname(docPath);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(docPath, content);
      count++;
    }

    return count;
  }

  private renderFileDoc(filePath: string, symbols: Symbol[], includeSource: boolean, includeDiagrams: boolean): string {
    const parts: string[] = [];

    // Header
    parts.push(`# ${filePath}`);
    parts.push('');
    parts.push(`> Auto-generated by CodeAtlas`);
    parts.push('');

    // Module info
    const languages = [...new Set(symbols.map(s => s.language))];
    parts.push(`**Language:** ${languages.join(', ')}`);
    parts.push(`**Symbols:** ${symbols.length}`);
    parts.push('');

    // Mermaid diagram for this file's internal relationships
    if (includeDiagrams && symbols.length > 1) {
      parts.push('## Internal Structure');
      parts.push('');
      parts.push('```mermaid');
      parts.push('graph TD');
      for (const sym of symbols) {
        const rels = this.store.getRelationshipsFrom(sym.id);
        for (const rel of rels) {
          if (rel.kind === 'contains' || rel.kind === 'calls') {
            const target = this.store.getSymbol(rel.targetId);
            if (target && target.filePath === filePath) {
              parts.push(`    ${this.mermaidId(sym)} -->|${rel.kind}| ${this.mermaidId(target)}`);
            }
          }
        }
      }
      parts.push('```');
      parts.push('');
    }

    // Symbols by kind
    const byKind = new Map<string, Symbol[]>();
    for (const sym of symbols) {
      if (!byKind.has(sym.kind)) byKind.set(sym.kind, []);
      byKind.get(sym.kind)!.push(sym);
    }

    const kindOrder = ['class', 'interface', 'enum', 'type', 'function', 'method', 'variable', 'constant'];
    for (const kind of kindOrder) {
      const kindSymbols = byKind.get(kind);
      if (!kindSymbols || kindSymbols.length === 0) continue;

      parts.push(`## ${this.capitalize(kind)}s`);
      parts.push('');

      for (const sym of kindSymbols) {
        parts.push(this.renderSymbolDoc(sym, includeSource));
      }
    }

    // Remaining kinds not in order
    for (const [kind, kindSymbols] of byKind) {
      if (kindOrder.includes(kind)) continue;
      parts.push(`## ${this.capitalize(kind)}s`);
      parts.push('');
      for (const sym of kindSymbols) {
        parts.push(this.renderSymbolDoc(sym, includeSource));
      }
    }

    return parts.join('\n');
  }

  private renderSymbolDoc(sym: Symbol, includeSource: boolean): string {
    const parts: string[] = [];

    parts.push(`### \`${sym.name}\``);
    parts.push('');

    // Metadata
    const meta: string[] = [];
    meta.push(`- **Kind:** ${sym.kind}`);
    meta.push(`- **Layer:** ${sym.layer}`);
    meta.push(`- **Lines:** ${sym.startLine}-${sym.endLine}`);
    if (sym.exported) meta.push(`- **Exported:** yes`);
    if (sym.complexity) meta.push(`- **Complexity:** ${sym.complexity}`);
    parts.push(meta.join('\n'));
    parts.push('');

    // Signature (extracted from source)
    if (sym.sourceCode) {
      const sig = this.extractSignature(sym.sourceCode, sym.kind);
      if (sig) {
        parts.push('**Signature:**');
        parts.push('```');
        parts.push(sig);
        parts.push('```');
        parts.push('');
      }
    }

    // Doc comment
    if (sym.docComment) {
      parts.push(`> ${sym.docComment}`);
      parts.push('');
    }

    // AI summary
    if (sym.aiSummary) {
      parts.push(`**Description:** ${sym.aiSummary}`);
      parts.push('');
    }

    // Callers/Callees
    const callers = this.store.getCallers(sym.id);
    const callees = this.store.getCallees(sym.id);

    if (callers.length > 0 || callees.length > 0) {
      parts.push('**Dependencies:**');
      if (callers.length > 0) {
        parts.push(`- Called by: ${callers.map(c => `\`${c.name}\``).join(', ')}`);
      }
      if (callees.length > 0) {
        parts.push(`- Calls: ${callees.map(c => `\`${c.name}\``).join(', ')}`);
      }
      parts.push('');
    }

    // Source code
    if (includeSource && sym.sourceCode) {
      parts.push('<details>');
      parts.push('<summary>Source Code</summary>');
      parts.push('');
      parts.push('```');
      parts.push(sym.sourceCode);
      parts.push('```');
      parts.push('</details>');
      parts.push('');
    }

    return parts.join('\n');
  }

  // ========================
  // Module-level docs
  // ========================

  private async generateModuleDocs(
    symbols: Symbol[],
    outputDir: string,
    includeSource: boolean,
    includeDiagrams: boolean,
  ): Promise<number> {
    // Group by directory (module)
    const byModule = new Map<string, Symbol[]>();
    for (const sym of symbols) {
      const parts = sym.filePath.split('/');
      const modulePath = parts.length > 2 ? parts.slice(0, -1).join('/') : parts[0];
      if (!byModule.has(modulePath)) byModule.set(modulePath, []);
      byModule.get(modulePath)!.push(sym);
    }

    let count = 0;
    for (const [modulePath, moduleSymbols] of byModule) {
      const content = this.renderModuleDoc(modulePath, moduleSymbols, includeSource, includeDiagrams);
      const docPath = path.join(outputDir, this.sanitizeFilename(modulePath) + '.md');
      const dir = path.dirname(docPath);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(docPath, content);
      count++;
    }

    return count;
  }

  private renderModuleDoc(modulePath: string, symbols: Symbol[], includeSource: boolean, includeDiagrams: boolean): string {
    const parts: string[] = [];

    parts.push(`# ${modulePath}`);
    parts.push('');
    parts.push(`> Auto-generated by CodeAtlas`);
    parts.push('');

    // Summary
    const byKind = new Map<string, number>();
    for (const sym of symbols) {
      byKind.set(sym.kind, (byKind.get(sym.kind) || 0) + 1);
    }
    parts.push(`**Symbols:** ${symbols.length}`);
    parts.push(`**Breakdown:** ${Array.from(byKind.entries()).map(([k, v]) => `${v} ${k}s`).join(', ')}`);
    parts.push('');

    // Dependency diagram
    if (includeDiagrams) {
      parts.push('## Module Dependencies');
      parts.push('');
      parts.push('```mermaid');
      parts.push('graph LR');

      const externalDeps = new Set<string>();
      for (const sym of symbols) {
        const rels = this.store.getRelationshipsFrom(sym.id);
        for (const rel of rels) {
          if (rel.kind === 'imports') {
            const target = this.store.getSymbol(rel.targetId);
            if (target && !target.filePath.startsWith(modulePath)) {
              const targetModule = target.filePath.split('/').slice(0, -1).join('/');
              if (targetModule !== modulePath) {
                externalDeps.add(targetModule);
                parts.push(`    ${this.mermaidId(sym)} -->|imports| ${this.sanitizeFilename(targetModule)}`);
              }
            }
          }
        }
      }
      parts.push('```');
      parts.push('');
    }

    // Symbols list
    parts.push('## Symbols');
    parts.push('');
    for (const sym of symbols) {
      const exported = sym.exported ? ' 📤' : '';
      parts.push(`- **\`${sym.name}\`** (${sym.kind}${exported}) — ${sym.filePath}:${sym.startLine}`);
      if (sym.aiSummary) {
        parts.push(`  > ${sym.aiSummary}`);
      }
    }
    parts.push('');

    return parts.join('\n');
  }

  // ========================
  // Index generation
  // ========================

  private generateIndex(symbols: Symbol[], outputDir: string, includeDiagrams: boolean): void {
    const parts: string[] = [];

    parts.push('# Project Documentation');
    parts.push('');
    parts.push('> Auto-generated by CodeAtlas');
    parts.push('');

    // Stats
    const byKind = new Map<string, number>();
    const byLayer = new Map<string, number>();
    const byLang = new Map<string, number>();
    for (const sym of symbols) {
      byKind.set(sym.kind, (byKind.get(sym.kind) || 0) + 1);
      byLayer.set(sym.layer, (byLayer.get(sym.layer) || 0) + 1);
      byLang.set(sym.language, (byLang.get(sym.language) || 0) + 1);
    }

    parts.push('## Overview');
    parts.push('');
    parts.push(`- **Total Symbols:** ${symbols.length}`);
    parts.push(`- **Languages:** ${Array.from(byLang.entries()).map(([l, c]) => `${l} (${c})`).join(', ')}`);
    parts.push('');

    parts.push('### By Kind');
    for (const [kind, count] of byKind) {
      parts.push(`- ${kind}: ${count}`);
    }
    parts.push('');

    parts.push('### By Layer');
    for (const [layer, count] of byLayer) {
      parts.push(`- ${layer}: ${count}`);
    }
    parts.push('');

    // Architecture diagram
    if (includeDiagrams) {
      parts.push('## Architecture');
      parts.push('');
      parts.push('```mermaid');
      parts.push('graph TB');
      parts.push('    subgraph Interface');
      const interfaceSymbols = symbols.filter(s => s.layer === 'interface').slice(0, 5);
      for (const s of interfaceSymbols) {
        parts.push(`        ${this.mermaidId(s)}`);
      }
      parts.push('    end');
      parts.push('    subgraph Business');
      const businessSymbols = symbols.filter(s => s.layer === 'business').slice(0, 5);
      for (const s of businessSymbols) {
        parts.push(`        ${this.mermaidId(s)}`);
      }
      parts.push('    end');
      parts.push('    subgraph Data');
      const dataSymbols = symbols.filter(s => s.layer === 'data').slice(0, 5);
      for (const s of dataSymbols) {
        parts.push(`        ${this.mermaidId(s)}`);
      }
      parts.push('    end');
      parts.push('```');
      parts.push('');
    }

    // File index
    const byFile = new Map<string, number>();
    for (const sym of symbols) {
      byFile.set(sym.filePath, (byFile.get(sym.filePath) || 0) + 1);
    }

    parts.push('## Files');
    parts.push('');
    const sortedFiles = Array.from(byFile.entries()).sort((a, b) => b[1] - a[1]);
    for (const [file, count] of sortedFiles) {
      parts.push(`- [\`${file}\`](${this.sanitizeFilename(file)}.md) — ${count} symbols`);
    }
    parts.push('');

    fs.writeFileSync(path.join(outputDir, 'INDEX.md'), parts.join('\n'));
  }

  // ========================
  // Helpers
  // ========================

  private extractSignature(sourceCode: string, kind: SymbolKind): string | null {
    const lines = sourceCode.split('\n');

    for (const line of lines) {
      const trimmed = line.trim();

      // Match function/method signatures
      if (kind === 'function' || kind === 'method') {
        const match = trimmed.match(/^(export\s+)?(async\s+)?(function\s+\w+|[\w.]+\s*=\s*(?:async\s+)?(?:function|\([^)]*\)\s*=>)|\w+\s*\([^)]*\)(?:\s*:\s*\w+)?)/);
        if (match) return match[0].trim();
      }

      // Match class signatures
      if (kind === 'class') {
        const match = trimmed.match(/^(export\s+)?(abstract\s+)?class\s+\w+/);
        if (match) return match[0].trim();
      }

      // Match interface/type/enum
      if (['interface', 'type', 'enum'].includes(kind)) {
        const match = trimmed.match(/^(export\s+)?(interface|type|enum)\s+\w+/);
        if (match) return match[0].trim();
      }

      // Match variable/constant
      if (kind === 'variable' || kind === 'constant') {
        const match = trimmed.match(/^(export\s+)?(const|let|var)\s+\w+/);
        if (match) return match[0].trim();
      }
    }

    // Fallback: first non-empty, non-comment line
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('//') && !trimmed.startsWith('#') && !trimmed.startsWith('/*') && !trimmed.startsWith('*')) {
        return trimmed.substring(0, 120);
      }
    }

    return null;
  }

  private mermaidId(sym: Symbol): string {
    return sym.name.replace(/[^a-zA-Z0-9]/g, '_');
  }

  private sanitizeFilename(name: string): string {
    return name.replace(/[/\\:]/g, '_').replace(/\.md$/, '');
  }

  private capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }
}
